package tradingstore

const ASSET_CLASS_CURRENCY = "CURRENCY"
const ASSET_CLASS_ETF = "ETF"
const ASSET_CLASS_INDEX = "INDEX"
const ASSET_CLASS_REIT = "REIT"
const ASSET_CLASS_STOCK = "STOCK"
const ASSET_CLASS_UNKNOWN = "UNKNOWN"

const COLUMN_ASSET_CLASS = "asset_class"
const COLUMN_CLOSE = "close"
const COLUMN_CREATED_AT = "created_at"
const COLUMN_DESCRIPTION = "description"
const COLUMN_EXCHANGE = "exchange"
const COLUMN_ID = "id"
const COLUMN_SYMBOL = "symbol"
const COLUMN_HIGH = "high"
const COLUMN_LOW = "low"
const COLUMN_OPEN = "open"
const COLUMN_SOFT_DELETED_AT = "soft_deleted_at"
const COLUMN_TIME = "time"
const COLUMN_TIMEFRAMES = "timeframes"
const COLUMN_UPDATED_AT = "updated_at"
const COLUMN_VOLUME = "volume"

const NIL_FLOAT = -0.0000000001

const TIMEFRAME_1_MINUTE = "1min"
const TIMEFRAME_5_MINUTES = "5min"
const TIMEFRAME_15_MINUTES = "15min"
const TIMEFRAME_30_MINUTES = "30min"
const TIMEFRAME_1_HOUR = "1hour"
const TIMEFRAME_4_HOURS = "4hour"
const TIMEFRAME_1_DAY = "1day"
const TIMEFRAME_1_WEEK = "1week"
const TIMEFRAME_1_MONTH = "1month"
const TIMEFRAME_1_YEAR = "1year"
